CREATE TABLE "BOOKMARK_GROUP1" (
	"ID"	INTEGER,
	"NAME"	TEXT NOT NULL UNIQUE,
	"ORDERS"	INTEGER UNIQUE,
	"ADD_DATE"	TEXT DEFAULT (DATETIME('NOW','LOCALTIME')),
	"EDIT_DATE"	INTEGER,
	PRIMARY KEY("ID" AUTOINCREMENT)
);