CREATE TABLE "TEMP1" (
	"ID"	INTEGER,
	"GROUP_ID"	INTEGER,
	"MANAGE_ID"	TEXT NOT NULL,
	"DATE"	TEXT NOT NULL DEFAULT (DATETIME('NOW','LOCALTIME')),
	PRIMARY KEY("ID" AUTOINCREMENT)
	FOREIGN KEY("GROUP_ID") REFERENCES BOOKMARK_GROUP(ID) ON DELETE CASCADE
	FOREIGN KEY("MANAGE_ID") REFERENCES RAW_DATA(MANAGE_ID) ON DELETE CASCADE
);